version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "5002:2000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./front
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5002
    depends_on:
      - backend
    restart: always

  admin:
    build: ./brzk_admin
    ports:
      - "5173:3001"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5002
    depends_on:
      - backend
    restart: always 